export {default as HomePage} from "./HomePage"
export {default as CoursesPage} from "./CoursesPage"
export {default as LoginPage} from "./LoginPage"
export {default as RegisterPage} from "./RegistrationPage"
export {default as TeacherPage} from "./TeacherPage"
export {default as AddmissionPage} from "./AddmissionPage"